[tool.poetry]
name = "operation-research"
version = "0.1.0"
description = ""
authors = ["Lan Nguyen <ndolanvn@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ortools = "^9.8.3296"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
